<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="101" started-at="2017-07-19T02:03:19Z" finished-at="2017-07-19T02:03:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="101" started-at="2017-07-19T02:03:19Z" finished-at="2017-07-19T02:03:19Z">
      <class name="functionGenerator.TestNG_Run">
        <test-method status="PASS" signature="beforetest()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="beforetest" is-config="true" duration-ms="14" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="beforemethod" is-config="true" duration-ms="0" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="atestrun()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="atestrun" duration-ms="32" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- atestrun -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="aftermethod" is-config="true" duration-ms="12" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="beforemethod" is-config="true" duration-ms="0" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="btestrun()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="btestrun" duration-ms="5" started-at="2017-07-18T22:03:19Z" depends-on-methods="functionGenerator.TestNG_Run.atestrun" finished-at="2017-07-18T22:03:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Tst] but found [Test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Tst] but found [Test]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at functionGenerator.TestNG_Run.btestrun(TestNG_Run.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btestrun -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="aftermethod" is-config="true" duration-ms="0" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:functionGenerator.TestNG_Run@4de8b406]" name="aftertest" is-config="true" duration-ms="1" started-at="2017-07-18T22:03:19Z" finished-at="2017-07-18T22:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- functionGenerator.TestNG_Run -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
